volumes:
  n8n_storage:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    env_file:
      - ./.env
    volumes:
      - n8n_storage:/home/node/.n8n

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
    - "80:80"
    - "443:443" # For HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # NGINX configuration
      - ./nginx/ssl:/etc/nginx/ssl:ro # SSL certificates (if using HTTPS)
    depends_on:
      - n8n # Ensure n8n starts before NGINX
